// apps/hopefull-admin/src/pages/dashboard/Dashboard.tsx
import { Users, Stethoscope, Calendar, DollarSign, TrendingUp, Clock } from 'lucide-react';
import { formatCurrency } from '../../lib/utils';

const stats = [
  { name: 'Total Users', value: '12,345', icon: Users, change: '+12%', color: 'bg-blue-500' },
  { name: 'Active Therapists', value: '234', icon: Stethoscope, change: '+5%', color: 'bg-green-500' },
  { name: 'Appointments Today', value: '89', icon: Calendar, change: '+18%', color: 'bg-purple-500' },
  { name: 'Revenue (Month)', value: '$45,230', icon: DollarSign, change: '+23%', color: 'bg-yellow-500' },
];

const recentActivities = [
  { type: 'user', message: 'New user registered: john.doe@email.com', time: '2 minutes ago' },
  { type: 'therapist', message: 'Dr. Sarah Smith completed verification', time: '15 minutes ago' },
  { type: 'appointment', message: 'New appointment booked (#APT-1234)', time: '32 minutes ago' },
  { type: 'payment', message: 'Payment received: $120.00', time: '1 hour ago' },
  { type: 'therapist', message: 'New therapist application: Dr. Mike Johnson', time: '2 hours ago' },
];

const pendingVerifications = [
  { id: 1, name: 'Dr. Emily Brown', email: 'emily.brown@email.com', date: '2024-01-07' },
  { id: 2, name: 'Dr. James Wilson', email: 'james.wilson@email.com', date: '2024-01-07' },
  { id: 3, name: 'Dr. Lisa Chen', email: 'lisa.chen@email.com', date: '2024-01-06' },
];

export default function Dashboard() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Dashboard</h1>
        <p className="text-sm text-gray-500">Welcome back! Here's what's happening.</p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {stats.map((stat) => (
          <div key={stat.name} className="card p-6">
            <div className="flex items-center justify-between">
              <div className={`${stat.color} p-3 rounded-lg`}>
                <stat.icon className="h-6 w-6 text-white" />
              </div>
              <span className="flex items-center text-sm font-medium text-green-600">
                <TrendingUp className="h-4 w-4 mr-1" />
                {stat.change}
              </span>
            </div>
            <div className="mt-4">
              <p className="text-2xl font-bold text-gray-900">{stat.value}</p>
              <p className="text-sm text-gray-500">{stat.name}</p>
            </div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
        {/* Recent Activity */}
        <div className="card">
          <div className="px-6 py-4 border-b border-gray-200">
            <h2 className="text-lg font-semibold text-gray-900">Recent Activity</h2>
          </div>
          <div className="divide-y divide-gray-200">
            {recentActivities.map((activity, index) => (
              <div key={index} className="px-6 py-4">
                <div className="flex items-start justify-between">
                  <p className="text-sm text-gray-900">{activity.message}</p>
                  <span className="flex items-center text-xs text-gray-500 whitespace-nowrap ml-4">
                    <Clock className="h-3 w-3 mr-1" />
                    {activity.time}
                  </span>
                </div>
              </div>
            ))}
          </div>
          <div className="px-6 py-4 border-t border-gray-200">
            <button className="text-sm font-medium text-primary-600 hover:text-primary-700">
              View all activity
            </button>
          </div>
        </div>

        {/* Pending Verifications */}
        <div className="card">
          <div className="px-6 py-4 border-b border-gray-200">
            <h2 className="text-lg font-semibold text-gray-900">
              Pending Therapist Verifications
            </h2>
          </div>
          <div className="divide-y divide-gray-200">
            {pendingVerifications.map((therapist) => (
              <div key={therapist.id} className="px-6 py-4">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm font-medium text-gray-900">{therapist.name}</p>
                    <p className="text-sm text-gray-500">{therapist.email}</p>
                  </div>
                  <button className="btn btn-primary text-xs px-3 py-1">
                    Review
                  </button>
                </div>
              </div>
            ))}
          </div>
          <div className="px-6 py-4 border-t border-gray-200">
            <button className="text-sm font-medium text-primary-600 hover:text-primary-700">
              View all pending ({pendingVerifications.length})
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// apps/vue-remote/src/components/Dashboard/Dashboard.vue
<template>
  <div class="space-y-6">
    <div class="grid md:grid-cols-4 gap-4">
      <StatsWidget
        v-for="stat in stats"
        :key="stat.label"
        :label="stat.label"
        :value="stat.value"
        :change="stat.change"
        :icon="stat.icon"
      />
    </div>

    <div class="grid lg:grid-cols-2 gap-6">
      <AnalyticsChart title="Revenue Overview" :data="revenueData" />
      <AnalyticsChart title="User Growth" :data="userData" color="green" />
    </div>

    <div class="bg-white rounded-xl shadow-sm p-6">
      <h3 class="text-lg font-semibold mb-4">Recent Activity</h3>
      <div class="space-y-3">
        <div
          v-for="activity in activities"
          :key="activity.id"
          class="flex items-center gap-4 p-3 hover:bg-gray-50 rounded-lg"
        >
          <div
            :class="[
              'w-10 h-10 rounded-full flex items-center justify-center text-white',
              activity.color,
            ]"
          >
            {{ activity.icon }}
          </div>
          <div class="flex-1">
            <p class="font-medium text-gray-900">{{ activity.title }}</p>
            <p class="text-sm text-gray-500">{{ activity.time }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import StatsWidget from '../Stats/StatsWidget.vue';
import AnalyticsChart from '../Charts/AnalyticsChart.vue';

const stats = ref([
  { label: 'Total Revenue', value: '$45,231', change: '+20.1%', icon: '$' },
  { label: 'Active Users', value: '2,350', change: '+15.3%', icon: '👥' },
  { label: 'Conversion Rate', value: '3.2%', change: '+4.5%', icon: '📈' },
  { label: 'Avg. Order Value', value: '$125', change: '-2.4%', icon: '🛒' },
]);

const revenueData = ref([30, 45, 35, 50, 40, 60, 55, 70, 65, 80, 75, 90]);
const userData = ref([100, 150, 200, 180, 250, 300, 280, 350, 400, 380, 450, 500]);

const activities = ref([
  {
    id: 1,
    icon: '🛒',
    title: 'New order #1234',
    time: '2 minutes ago',
    color: 'bg-blue-500',
  },
  {
    id: 2,
    icon: '👤',
    title: 'New user registration',
    time: '15 minutes ago',
    color: 'bg-green-500',
  },
  {
    id: 3,
    icon: '💬',
    title: 'Support ticket resolved',
    time: '1 hour ago',
    color: 'bg-purple-500',
  },
  {
    id: 4,
    icon: '📦',
    title: 'Order shipped #1230',
    time: '2 hours ago',
    color: 'bg-orange-500',
  },
]);
</script>
